### ISSUE TITLE
Feature: Add RSS feed support

### ISSUE THREAD

**Issue by davidlunadeleon** [davidlunadeleon/gatsby-blog-template#1]
**Feature:** Add RSS Feed to blog using gatsby-plugin-feed.

**TODO:**

- [x] Add feed plugin to generate RSS  feed.
- [x] Add useful link to RSS feed in footer component.
- [x] Add author data to blog posts.

**Useful guide:** https://www.gatsbyjs.com/docs/adding-an-rss-feed/#reach-skip-nav
