### ISSUE TITLE
Feature: Add multiple language support

### ISSUE THREAD

**Issue by davidlunadeleon** [davidlunadeleon/gatsby-blog-template#2]
**Feature:** Add support to select language in website

**TODO:**

- [x] Add config file to specify supported languages.
- [x] Add language selection button to navbar.
- [x] Modify gatsby-node.js to generate pages appropriately.
- [x] Add blog post examples to show multiple language support. 
- [x] Make language specific RSS feeds
- [x] Link different generated feeds in footer links
- [x] Add language to RSS feed name
- [x] Display appropriate language posts in homepage
- [x] Display appropriate language posts when viewing tags

**Useful guide:** 
- https://medium.com/better-programming/multiple-language-websites-with-gatsbyjs-b4985746b9eb
- https://github.com/wiziple/gatsby-plugin-intl/issues/17
