### ISSUE TITLE
Feature: Add dark theme

### ISSUE THREAD

**Issue by davidlunadeleon** [davidlunadeleon/gatsby-blog-template#3]
**Feature:** Add dark theme selection

**TODO:**

- [ ] Add theme selection button in navbar.
- [ ] Modify component appropriately.
- [ ] Test icon colors with dark theme.
- [ ] Set buttons and blog post titles color with bootstrap.
